### ISSUE TITLE
Fails on UTF-16 input [was: Failed to add text in UTF-16]

### ISSUE THREAD

**Issue by jgclark** [kopischke/mmd2en#2]
Using the app, sometimes the MD or MMD content is blank except for one or a few characters, starting with 'þ'. It also has the timestamp for the note name, rather than the filename. I suspect this is happening when the file type is UTF-16 not ASCII.

When I do a conversion of the file to UTF-8:

```
iconv -f UTF-16 -t UTF-8 in.md > out.md
```

then the file is added to EN without problems.

**Comment by kopischke** [comment]
Thanks for participating in the beta and filing this issue. Could you please provide me with an UTF-16 encoded file on which conversion fails, either as a downloadable archive somewhere (Dropbox. CloudApp, Droplr, whatever works for you) or via the email address listed on the [Contact section of the wiki](https://github.com/kopischke/mmd2en/wiki/Project-Information#%23giving-non-bug-feedback)?

**Comment by jgclark** [comment]
Here's an example file (as for Issue #1): https://www.dropbox.com/s/a5pzqy28v3c97f1/Alpha%2015%20-%20Suffering%20and%20the%20Problem%20of%20Evil.md

**Comment by kopischke** [comment]
Thanks for the upload. Your diagnosis is correct: UTF-16 files are not processed correctly. The empty note is due to   `multimarkdown` being unable to convert the files to HTML, and the missing metadata is due to my own parser implementations relying on the locale encoding for their processing. I have been able to work around both issues by leveraging Ruby’s transcoding abilities, and the next _mmd2en_ release should process all flavours of UTF without trouble.

**Comment by jgclark** [comment]
That was quick work, thanks! I look forward to testing the revised version in due course.
