### ISSUE TITLE
Include file system information in metadata 

### ISSUE THREAD

**Issue by kopischke** [kopischke/mmd2en#4]
_mmd2en_’s metadata collection strategy as of 2.0.0rc1 does not include relevant file system data for processed files (the file name, Mavericks tags, OM tags and Finder info come to mind). The exclusion of this information from collected metadata runs against user expectations (see issue #1, #3) and should be remedied.

**Comment by jgclark** [comment]
Thanks for the clarification on the current strategy.

I would suggest putting filename (minus the extension) plus the datestamp as the fallback option, rather than just datestamp. Often the filename will be meaningful, but I can imagine occasions for some users where it won't be, and having datestamp might help. Personally I would shorten the datestamp to something more like "15 April 2011 00:17".

Separately, I would suggest taking the Mavericks and OM tags and adding them as EN tags, alongside any MMD tags.

**Comment by kopischke** [comment]
Yeah, those were the items I was thinking of too: Finder comments really are not mappable to any metadata field, and file date stamps are too problematic to be considered useful, so that leaves the file name proper and tags.

As to the date stamp, I tend towards leaving that as the default for notes created from text selection only. The date stamp was a necessity as long as title metadata could be empty, as Evernote does not allow for creating notes without a title, but that point is now moot. With the note creation date set by Evernote itself and exposed in both the note properties UI and the search UI, adding it explicitly seems redundant.

**Comment by jgclark** [comment]
Hi, kopischke. Any news on when you might issue a new build of this, incorporating the updates you did as a result of this issue?

Thanks,

Jonathan
